version: 2.1

orbs:
  queue: eddiewebb/queue@volatile

workflows:
  build_and_publish:
    jobs:
      - queue/block_workflow:
          context: pierissimo
          only-on-branch: master
          time: "10" # minutes max wait
      - build:
          context: pierissimo
          requires:
            - queue/block_workflow

jobs:
  build:
    docker:
      - image: circleci/node:16-stretch
      - image: circleci/mongo:4.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-npm-deps-{{ .Branch }}
            - v2-npm-deps-
      - run:
          name: install NPM dependencies
          command: yarn
      - save_cache:
          key: v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: test
          command: yarn cover
      - run:
          name: build
          command: yarn build
      - run:
          name: upload coverage report
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      # disabled as builds blocked by security vulnerability in developer dependency: semantic-release
      #   - run:
      #     name: audit
      #     command: npm audit
      - run:
          name: allow same version
          command: npm config set allow-same-version true
      - run:
          name: do a release
          command: npx semantic-release
